-- Database seed for Fade Boba

-- Clear existing data if needed (Optional, but good for clean start during development)
-- TRUNCATE TABLE Menu_Items, Inventory, Order_Line_Items, Orders, Employees, Customers RESTART IDENTITY CASCADE;

-- 1. SEED EMPLOYEES
INSERT INTO Employees (first_name, last_name, role, pin, email) VALUES
('Alice', 'Manager', 'Manager', '1234', 'alice.manager@example.com'),
('Bob', 'Cashier', 'Cashier', '0001', 'bob.cashier@example.com'),
('Charlie', 'Staff', 'Cashier', '1111', 'charlie.staff@example.com'),
('David', 'Admin', 'Manager', '9999', 'david.admin@example.com')
ON CONFLICT (email) DO NOTHING;

-- 2. SEED MENU ITEMS (Drinks)
INSERT INTO Menu_Items (item_name, base_price, item_type) VALUES
('Classic Milk Tea', 4.50, 'Drink'),
('Thai Milk Tea', 4.75, 'Drink'),
('Taro Milk Tea', 4.75, 'Drink'),
('Brown Sugar Boba', 5.25, 'Drink'),
('Matcha Latte', 5.50, 'Drink'),
('Mango Green Tea', 4.25, 'Drink'),
('Strawberry Slush', 5.00, 'Drink'),
('Passion Fruit Green Tea', 4.25, 'Drink'),
('Wintermelon Milk Tea', 4.50, 'Drink'),
('Rose Milk Tea', 4.75, 'Drink'),
('Oolong Milk Tea', 4.50, 'Drink'),
('Jasmine Milk Tea', 4.50, 'Drink'),
('Lychee Green Tea', 4.25, 'Drink'),
('Peach Green Tea', 4.25, 'Drink'),
('Grapefruit Green Tea', 4.25, 'Drink'),
('Chocolate Milk Tea', 4.75, 'Drink'),
('Coffee Milk Tea', 5.00, 'Drink'),
('Caramel Milk Tea', 5.00, 'Drink'),
('Hazelnut Milk Tea', 5.00, 'Drink'),
('Vanilla Milk Tea', 4.75, 'Drink'),
('Honeydew Milk Tea', 4.75, 'Drink'),
('Coconut Milk Tea', 4.75, 'Drink'),
('Watermelon Slush', 5.25, 'Drink'),
('Pineapple Slush', 5.25, 'Drink'),
('Dragonfruit Slush', 5.50, 'Drink'),
('Kiwi Fruit Tea', 4.50, 'Drink'),
('Blueberry Fruit Tea', 4.50, 'Drink'),
('Raspberry Fruit Tea', 4.50, 'Drink'),
('Mixed Berry Slush', 5.50, 'Drink'),
('Avocado Smoothie', 6.00, 'Drink'),
('Mango Smoothie', 5.50, 'Drink'),
('Banana Smoothie', 5.25, 'Drink'),
('Papaya Smoothie', 5.50, 'Drink'),
('Durian Smoothie', 7.50, 'Drink'),
('Ginger Tea', 4.00, 'Drink'),
('Chrysanthemum Tea', 4.00, 'Drink'),
('Peppermint Tea', 4.00, 'Drink'),
('Earl Grey Milk Tea', 4.75, 'Drink'),
('Chai Milk Tea', 5.00, 'Drink'),
('Lavender Milk Tea', 4.75, 'Drink'),
('Sakura Milk Tea', 5.25, 'Drink'),
('Blue Pea Tea', 4.75, 'Drink'),
('Thai Green Milk Tea', 5.00, 'Drink'),
('Brown Sugar Ginger Tea', 5.00, 'Drink'),
('Kumquat Green Tea', 4.50, 'Drink'),
('Lemon Green Tea', 4.25, 'Drink'),
('Yakult Green Tea', 5.00, 'Drink'),
('Yakult Strawberry', 5.50, 'Drink'),
('Yakult Mango', 5.50, 'Drink'),
('Yakult Lychee', 5.50, 'Drink'),
('Red Bean Milk Tea', 5.00, 'Drink'),
('Pudding Milk Tea', 5.25, 'Drink'),
('Grass Jelly Milk Tea', 5.00, 'Drink'),
('Herbal Tea', 4.50, 'Drink'),
('Honey Green Tea', 4.00, 'Drink'),
('Honey Oolong Tea', 4.00, 'Drink'),
('Lemon Wintermelon', 4.50, 'Drink'),
('Orange Green Tea', 4.50, 'Drink'),
('Mango Pomelo Sago', 6.50, 'Drink'),
('Brown Sugar Matcha', 5.75, 'Drink'),
('Strawberry Milk', 5.00, 'Drink'),
('Banana Milk', 5.00, 'Drink'),
('Chocolate Slush', 5.25, 'Drink'),
('Coffee Slush', 5.50, 'Drink'),
('Mocha Latte', 5.75, 'Drink'),
('Vietnamese Coffee', 5.50, 'Drink'),
('Thai Coffee', 5.50, 'Drink'),
('White Peach Oolong', 4.75, 'Drink'),
('Tie Guan Yin Milk Tea', 5.00, 'Drink'),
('Phoenix Oolong', 5.25, 'Drink'),
('Longan Red Date Tea', 5.00, 'Drink'),
('Hibiscus Tea', 4.50, 'Drink'),
('Lemonade', 3.50, 'Drink'),
('Strawberry Lemonade', 4.25, 'Drink'),
('Mango Lemonade', 4.25, 'Drink'),
('Sparkling Peach', 4.75, 'Drink'),
('Sparkling Lychee', 4.75, 'Drink'),
('Sparkling Mango', 4.75, 'Drink'),
('Sparkling Strawberry', 4.75, 'Drink'),
('Hot Chocolate', 4.50, 'Drink'),
('Hot Matcha', 5.00, 'Drink'),
('Hot Taro', 4.75, 'Drink')
ON CONFLICT (item_name) DO NOTHING;

-- 3. SEED MENU ITEMS (Addons)
INSERT INTO Menu_Items (item_name, base_price, item_type) VALUES
('Tapioca Pearls (Boba)', 0.75, 'Addon'),
('Crystal Boba', 0.85, 'Addon'),
('Popping Boba Mango', 0.85, 'Addon'),
('Popping Boba Strawberry', 0.85, 'Addon'),
('Popping Boba Lychee', 0.85, 'Addon'),
('Popping Boba Peach', 0.85, 'Addon'),
('Popping Boba Blueberry', 0.85, 'Addon'),
('Grass Jelly', 0.65, 'Addon'),
('Ai-Yu Jelly', 0.65, 'Addon'),
('Lychee Jelly', 0.65, 'Addon'),
('Coffee Jelly', 0.65, 'Addon'),
('Coconut Jelly', 0.65, 'Addon'),
('Rainbow Jelly', 0.75, 'Addon'),
('Aloe Vera', 0.75, 'Addon'),
('Red Bean', 0.75, 'Addon'),
('Taro Mash', 1.00, 'Addon'),
('Egg Pudding', 0.75, 'Addon'),
('Cheese Foam', 1.25, 'Addon'),
('Sea Salt Foam', 1.25, 'Addon'),
('Whipped Cream', 0.75, 'Addon'),
('Oreos', 0.60, 'Addon'),
('Chocolate Chips', 0.60, 'Addon'),
('Caramel Drizzle', 0.50, 'Addon'),
('Brown Sugar Drizzle', 0.50, 'Addon'),
('Honey', 0.50, 'Addon'),
('Chia Seeds', 0.65, 'Addon'),
('Basil Seeds', 0.65, 'Addon')
ON CONFLICT (item_name) DO NOTHING;

-- 4. SEED INVENTORY (Ingredients & Supplies)
INSERT INTO Inventory (item_name, quantity_in_stock, reorder_level) VALUES
('Assam Black Tea Leaves (kg)', 10, 2),
('Jasmine Green Tea Leaves (kg)', 10, 2),
('Oolong Tea Leaves (kg)', 8, 2),
('Thai Tea Blend (kg)', 5, 1),
('Earl Grey Tea Leaves (kg)', 5, 1),
('Matcha Powder (kg)', 3, 0.5),
('Taro Powder (kg)', 5, 1),
('Roasted Coffee Beans (kg)', 10, 2),
('Whole Milk (L)', 50, 10),
('Oat Milk (L)', 20, 5),
('Almond Milk (L)', 15, 3),
('Soy Milk (L)', 15, 3),
('Condensed Milk (kg)', 12, 2),
('Non-dairy Creamer (kg)', 25, 5),
('Fructose Syrup (kg)', 30, 5),
('Brown Sugar Syrup (kg)', 20, 5),
('Honey Syrup (kg)', 10, 2),
('Wintermelon Syrup (kg)', 10, 2),
('Honeydew Syrup (kg)', 10, 2),
('Mango Jam/Purée (kg)', 15, 3),
('Strawberry Jam/Purée (kg)', 15, 3),
('Lychee Jam/Purée (kg)', 10, 2),
('Passion Fruit Jam/Purée (kg)', 10, 2),
('Peach Jam/Purée (kg)', 10, 2),
('Grapefruit Jam/Purée (kg)', 10, 2),
('Kiwi Jam/Purée (kg)', 5, 1),
('Dragonfruit Jam/Purée (kg)', 5, 1),
('Blueberry Jam/Purée (kg)', 5, 1),
('Durian Purée (kg)', 2, 0.5),
('Avocado (Box)', 5, 1),
('Banana (Bunch)', 10, 2),
('Yakult Bottles (Pack of 50)', 5, 1),
('Tapioca Pearls (Dry, kg)', 20, 5),
('Crystal Boba (kg)', 10, 2),
('Popping Boba Mango (kg)', 5, 1),
('Popping Boba Strawberry (kg)', 5, 1),
('Popping Boba Lychee (kg)', 5, 1),
('Grass Jelly (kg)', 10, 2),
('Aloe Vera (kg)', 10, 2),
('Red Bean (Canned)', 20, 4),
('Grass Jelly Powder (kg)', 5, 1),
('Egg Pudding Powder (kg)', 5, 1),
('Cheese Foam Powder (kg)', 3, 0.5),
('Heavy Cream (L)', 12, 2),
('Sea Salt (kg)', 2, 0.5),
('Sugar (White, kg)', 50, 10),
('Brown Sugar (kg)', 20, 4),
('Oreos (Crushed, kg)', 5, 1),
('Chocolate Chips (kg)', 5, 1),
('Chocolate Syrup (kg)', 5, 1),
('Caramel Syrup (kg)', 5, 1),
('Ice (kg)', 100, 20),
('Water (Gallons)', 500, 100),
('Plastic Cups - Large (case)', 20, 4),
('Plastic Cups - Medium (case)', 20, 4),
('Dome Lids (case)', 15, 3),
('Flat Lids (case)', 15, 3),
('Large Boba Straws (case)', 10, 2),
('Standard Straws (case)', 10, 2),
('Paper Napkins (case)', 5, 1),
('Cup Sleeves (case)', 5, 1),
('Sealing Film (Roll)', 10, 2),
('Trash Bags (box)', 10, 2),
('Gloves - Latex Free (box)', 20, 4),
('Cleaning Detergent (L)', 10, 2),
('Sanitizer Solution (L)', 10, 2)
ON CONFLICT (item_name) DO NOTHING;
